### ISSUE TITLE
Table Upload in the assets 

### ISSUE THREAD

**Issue by aldosales** [gee-community/gee_tools#10]
Hi folks, 

I am trying to upload a table in my asset, however, I couldn´t do it. I selected the dbf, shp, and shx files as described the GEE. after minutes of running the process, I received the warning message: Error: Unable to parse the specified file.

Can anyone help me?

**Comment by aldosales** [comment]
I think so, once that I am trying to upload an asset on GEE.

Universidade Federal de Pernambuco
Biomass energy research group
Post-Ph.D researcher
+55 83 996294911





2018-08-21 22:22 GMT-03:00 Rodrigo E. Principe <notifications@github.com>:

**Comment by fitoprincipe** [comment]
@aldosales this is an issue board for geetools, which is a python package with tools for google earth engine python API, but it's not the repository of it. You can post the code here if you want to be sure where should it go, but I reckon it's a question for the [original gee repo](https://github.com/google/earthengine-api/issues)
