### ISSUE TITLE
Composite module missing

### ISSUE THREAD

**Issue by e5k** [gee-community/gee_tools#21]
Hi there!

I am trying the notebooks attached with the master release. Just upgraded geetools using pip but I keep getting a:

`ImportError: cannot import name 'composite'`

I can import all other modules fine. I saw that the module composite was added 3 days ago, maybe it isn't yet available on pip?

Thanks!

**Comment by fitoprincipe** [comment]
Hi @e5k! Yes, you are right, it's not available in pip yet. You can test it installing it directly from the repository:

1. `pip uninstall geetools`
2. navigate to where the cloned repository is
3. `pip install .`

That should work. Let me know.

**Comment by e5k** [comment]
Brilliant, thanks so much for the super fast answer! And thanks for all the tools too!

**Comment by fitoprincipe** [comment]
You're welcome! And thank you for testing! It's great to know it's useful to someone else than me. =)

**Comment by e5k** [comment]
I know the feeling! Can I pick your brain on what I am trying to achieve?
