### ISSUE TITLE
Cannot find col2drive in geetools.tools

### ISSUE THREAD

**Issue by nerva-trajanvs** [gee-community/gee_tools#22]
Hi Rodrigo,

I am also trying to use geetools to download imageCollection. However, I cannot find col2drive function in geetools.tools. My code is below.  Thank you for your help and this powerful tool.

`from geetools import tools
import ee
ee.Initialize()
S1_images=ee.ImageCollection('COPERNICUS/S1_GRD').filterDate('2017-08-27','2017-08-29')
task = tools.col2drive(S1_images,r'D:\result')
`
I got the error message
AttributeError: module 'geetools.tools' has no attribute 'col2drive'

**Comment by fitoprincipe** [comment]
Hi @nerva-trajanvs, I have restructured the code.

``` python
from geetools import batch

S1_images=ee.ImageCollection('COPERNICUS/S1_GRD').filterDate('2017-08-27','2017-08-29')
batch.ImageCollection.toDrive(S1_images, folder='result', scale=10)
```

Let me know how it goes.

**Comment by fitoprincipe** [comment]
Hi @nerva-trajanvs, you can also export to Google Cloud Storage, but I haven't made a function to export an entire collection to cloud storage. If you make one you can fork and pull request :smile:
