### ISSUE TITLE
Copernicus/S2 imagery not working

### ISSUE THREAD

**Issue by maykef** [gee-community/gee_tools#24]
hey @fitoprincipe I'm working with geetools in jupyter, but I've got some problems with visualising Copernicus Sentinel 2 imagery. It works well with Landsat. I also noticed I cannot run ee.mapclient, it gives me this error:

`Exception in thread Thread-4: Traceback (most recent call last): File "/home/maykef/anaconda3/lib/python3.7/threading.py", line 917, in _bootstrap_inner self.run() File "/home/maykef/anaconda3/lib/python3.7/site-packages/ee/mapclient.py", line 125, in run self.parent = Tkinter.Tk() File "/home/maykef/anaconda3/lib/python3.7/tkinter/__init__.py", line 2023, in __init__ self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use) _tkinter.TclError: no display name and no $DISPLAY environment variable`

**Comment by fitoprincipe** [comment]
Hi @maykef, have you solved it?

**Comment by maykef** [comment]
Hi @fitoprincipe, yes I did. 

I just didn't add min-max in the add layer line.

In the same order of things, do you think a drawing polygon tool can be implemented? So you don't have to write the coordinates every single time?
