### ISSUE TITLE
Have you seen this weird error before?

### ISSUE THREAD

**Issue by maykef** [gee-community/gee_tools#25]
> `---------------------------------------------------------------------------
> IndexError                                Traceback (most recent call last)
> <ipython-input-2-bda6c4325f04> in <module>
>       1 from geetools import ui
>       2 
> ----> 3 Map = ui.Map()
>       4 Map.show()
> 
> ~/anaconda3/lib/python3.7/site-packages/geetools/ui/ipymap.py in __init__(self, tabs, **kwargs)
>      79 
>      80             # Asset Manager Widget
> ---> 81             asset_manager = ipytools.AssetManager(self)
>      82 
>      83             # Layers
> 
> ~/anaconda3/lib/python3.7/site-packages/geetools/ui/ipytools.py in __init__(self, map, **kwargs)
>     310         # Thumb height
>     311         self.thumb_height = kwargs.get('thumb_height', 300)
> --> 312         self.root_path = ee.data.getAssetRoots()[0]['id']
>     313 
>     314         # Map
> 
> IndexError: list index out of range`

**Comment by fitoprincipe** [comment]
Hi @maykef, what python version are you running?

**Comment by maykef** [comment]
3.7

**Comment by fitoprincipe** [comment]
I can't reproduce the error. I didn't have python 3.7 installed, but now that I have, I tested it and everything works as expected. What version of `geetools` are you running?

**Comment by maykef** [comment]
Rodrigo, 
I forgot to mention that this is within a conda env on a mac.

I am using the latest version of geetools.

I was actually reproducing locally a GCC VM (Ubuntu 16.04) where everything works perfectly, including geetools. So, the problem is just on my mac.

I hope that is clearer now

**Comment by fitoprincipe** [comment]
Ok, unfortunately I don't have access to a mac to test it.

Let's try something..

Make a new notebook (or just in terminal) and run:

``` python
import ee
ee.Initialize()

print(ee.data.getAssetRoots())
```

and tell me what is the output

**Comment by lancele** [comment]
I'm getting the same error as the original post, and I am also using anaconda:

``` 
import ee
ee.Initialize()
print(ee.data.getAssetRoots())
```

produces

```[]```

**Comment by fitoprincipe** [comment]
Hi @lancele , that is weird, what happens if you try the same command in the code editor? Just run `print(ee.data.getAssetRoots())`

**Comment by lancele** [comment]
If you mean the web GEE code editor, then running `print(ee.data.getAssetRoots())` yields the following on the console:

```javascript
[
  {
    "id": "users/planetes",
    "type": "Folder"
  }
]

```

**Comment by fitoprincipe** [comment]
It should be the same output for the Python API. You should report it to the [google earth engine issue tracker](https://github.com/google/earthengine-api/issues)

**Comment by torresrua** [comment]
Just for anybody who comes up with this error (like 5 students of mine). If print(ee.data.getAssetRoots()) returns [] or ipygee Map show fails, then go to the javascript web earth engine console, click on the asset tab (on the right) and make sure your asset folder exists (e.g. user/yourname/)

**Comment by fitoprincipe** [comment]
You are totally right! I didn't realize that you first have to "create" your asset root (it was so long ago when I first did it that I had forgotten!) Thank you @torresrua! Cheers =)

**Comment by arkanoid87** [comment]
this issue il live and kicking and should not be closed

the solution proposed by @torresrua is not working in my context.
I have `print(ee.data.getAssetRoots())` correctly returning list of length 1 in web editor, but `ee.data.getAssetRoots()` returns `[]` in python API, and apparently there no issue with credential permissions.
