### ISSUE TITLE
Ubuntu 18.04 installation fails

### ISSUE THREAD

**Issue by alexmyczko** [gee-community/gee_tools#26]
```
# pip install geetools
Collecting geetools
  Using cached https://files.pythonhosted.org/packages/51/83/3f6f6cc185902d27468dcbef69736d12244386ec26439cabb6a09a30f471/geetools-0.1.7.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-bitz479n/geetools/setup.py", line 5, in <module>
        from geetools import __version__
      File "/tmp/pip-build-bitz479n/geetools/geetools/__init__.py", line 17, in <module>
        from . import tools, bitreader, cloud_mask, expressions, decision_tree,\
      File "/tmp/pip-build-bitz479n/geetools/geetools/tools/__init__.py", line 3, in <module>
        from . import imagecollection, date, dictionary, image, number, \
      File "/tmp/pip-build-bitz479n/geetools/geetools/tools/imagecollection.py", line 3, in <module>
        import ee
      File "/usr/local/lib/python3.6/dist-packages/ee/__init__.py", line 1, in <module>
        from .main import main
      File "/usr/local/lib/python3.6/dist-packages/ee/main.py", line 10, in <module>
        import StringIO
    ModuleNotFoundError: No module named 'StringIO'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-bitz479n/geetools/
```
likewise with pip2, or pip3

**Comment by fitoprincipe** [comment]
Hi @alexmyczko, it seems to be an issue in the Google Earth Engine API. Try to install it first and see what happens.

**Comment by alexmyczko** [comment]
Could you please be more specific what I should do? We have CUDA 10 and Ubuntu 18.04. Is the instructions to be done with Python 2 or 3?

**Comment by fitoprincipe** [comment]
Ok. I'd recommend to use a virtual environment, so I guide you through this.

1. Make the Virtual Environment
  a. open a terminal in the path you want to have the virtual environment
  b. we'll name it `geepy3`, you can change that. Type:
    > vitrtualenv geepy3 --python=python3

2. activate your environment. Type:
    > . geepy3/bin/activate

3. Install google earth engine python API
    > pip install earthengine-api oauth2client

4. Test it
    > python -c "import ee; ee.Initialize()"

5. If it is the first time you run it, it will ask you to open a link and copy/paste a code...
6. Then you can install `geetools`. Type:
    > pip install pandas pygal ipyleaflet folium pyshp pillow requests geetools

Let me know how it goes =)

**Comment by fitoprincipe** [comment]
Hi @alexmyczko, did you make it run?

**Comment by KonstantinosF** [comment]
Hi @fitoprincipe 

I installed it successfully.

It was me having that problem in the first place and @alexmyczko was trying to help me.
Thanx.

**Comment by fitoprincipe** [comment]
Hi @KonstantinosF 

Great! Well, any other issue/comment, I am here =)

Best
Rodrigo
