### ISSUE TITLE
pip install geetools ERROR: ImportError: No module named shapefile

### ISSUE THREAD

**Issue by jepabe** [gee-community/gee_tools#29]
I am trying to install the Geetools library on datalab in docker, and the error occurs:
ImportError: No module named shapefile.
Someone has had something similar.
thank you!!

**Comment by fitoprincipe** [comment]
Hello @jepabe,
See https://github.com/gee-community/gee_tools/issues/26#issuecomment-472405182 and, if that doesn't work, tell me and we'll see.

**Comment by jepabe** [comment]
thank you very much for your quick response, today for me the world is a
better place to live ..
I'm with a Google Cloud Plattaform environment, where I have installed the
Gee libraries, in docker and I use datalab and the geetools library has
seemed essential to use in my environment, I've also seen in another forum
that you had problems installing GDAL, I also I'm suffering this, I think
that every day I dedicate an hour to my personal challenge of installing
GDAL in GCP ...

From already thank you very much!!
