### ISSUE TITLE
new to GEE python API

### ISSUE THREAD

**Issue by leigh-stearns** [gee-community/gee_tools#3]
Hi there -
Sorry to bug you with, what I am guessing, is a very basic question! I've been trying to piece together your code snippets from various StackExchange posts, but am likely missing something obvious. I'm using Spyder and have imported your gee_tools.
My task is simple! I want to download multiple L8 images (as many as available) of a small region in Greenland but am having trouble with the iterating part. I think I "should" be able to call your gee.ExportCol command as well, but I'm not sure where that fits in. 

kgl = ee.Geometry.Polygon(
        [[[-33.18145751953125, 68.63655326841952],
          [-32.79144287109375, 68.52722953172731],
          [-32.65960693359375, 68.58245935169703],
          [-32.95623779296875, 68.68951879149195]]])
start = '2016-05-01'
stop = '2016-06-01'
images = ee.ImageCollection("LANDSAT/LC8_L1T_TOA") \
    .filterBounds(kgl)
images = images.filterDate(start, stop)
listOfImages = images.toList(images.size());

After this snippet, I tried lots of variations of the task= ee.batch.Export.image.toDrive and gee.ExportCol...but I don't think I have my list set up correctly. Would appreciate any suggestions!

**Comment by fitoprincipe** [comment]
Hello Leigh,

ExportCol() is a JavaScript function to use in the code editor. If you are using python, you can use 2 functions: `col2asset` or `col2drive`

    from gee_tools_py import geetools
    
    # YOUR CODE
    kgl = ee.Geometry.Polygon(
    [[[-33.18145751953125, 68.63655326841952],
    [-32.79144287109375, 68.52722953172731],
    [-32.65960693359375, 68.58245935169703],
    [-32.95623779296875, 68.68951879149195]]])
    start = '2016-05-01'
    stop = '2016-06-01'
    images = ee.ImageCollection("LANDSAT/LC8_L1T_TOA") .filterBounds(kgl)
    images = images.filterDate(start, stop)
    
    # NEW
    myFolder = "SomeDriveFolder"
    geetools.col2drive(images, myFolder, region=kgl)
    
Try this and see what happens, any issues just come back.

**Comment by leigh-stearns** [comment]
Thank you so much! Saved me hours (days!) of tinkering with it! 

I do get the following error about the geometry:
try n° 7 ERROR: <ee.geometry.Geometry object at 0x1812f6b850> is not JSON serializable

Am I missing something in defining kgl? I also tried just:
kgl = ee.Geometry.Rectangle([-33.2, 68.68, -32.6, 68.52]);

but got the same error. Also, why doesn't it actually clip it in filterBounds? Again, thanks so much. You are being graciously helpful!

**Comment by fitoprincipe** [comment]
That is a good issue to solve in the code, i will. Meanwhile you can workaround just:
`geetools.col2drive(images, myFolder, region=kgl.getInfo()["coordinates"])`

If you consider my work/time worth some money, you can donate to paypal.me/rodrigoprincipe
Thank you!

**Comment by leigh-stearns** [comment]
Thanks again, that worked perfectly. I made a small donation to you on paypal - if I was richer I'd donate more!

**Comment by fitoprincipe** [comment]
That is great Leigh! thank you so much, it motivates me to keep working and helping. Have a nice day =)
