### ISSUE TITLE
Error in uploading shapefile

### ISSUE THREAD

**Issue by AyouCha** [gee-community/gee_tools#30]
Hello,
I am new user of GEE, I am trying to perform a supervised classification, so when I import my shapefile, I get the following error message : "Error: Unable to transform edge (549555.928576868,3474668.316669156 to 549555.9286273334,3474668.3166489694) from Planar EPSG:4326 to Geodesic EPSG:4326 (within 4.488328883882435E-5 units)"
I didn't understand, how can I transform it from Planar EPSG:4326 to Geodesic EPSG:4326 ?

Any help, Please?

AyouCha

**Comment by fitoprincipe** [comment]
Hi @AyouCha, this is related to [earthengine](https://github.com/google/earthengine-api). You can also ask in [here](https://gis.stackexchange.com/questions/tagged/google-earth-engine)

**Comment by janardanroy** [comment]
I am also having the same issue. Any solution?
