### ISSUE TITLE
Invalid GeoJSON geometry error 

### ISSUE THREAD

**Issue by Henrique165** [gee-community/gee_tools#35]
Hello!
I received a similar error message as reported on https://github.com/fitoprincipe/geetools-code-editor/issues/2 when trying to batch download an image collection, except on python. 
Here's the code:

`import ee
ee.Initialize()
from geetools import batch

feature = ee.Geometry.Polygon([[-20.3014885, -51.5035369], [-20.84233950, -51.6313196], [-20.6922002, -51.2336120], [-20.5804476, -52.1965132]]), {'site': 1}
fc = ee.FeatureCollection(feature)
collection = ee.ImageCollection("COPERNICUS/S5P/NRTI/L3_CLOUD").select('cloud_optical_depth').filterDate('2019-09-10', '2019-09-13').filterBounds(fc.geometry())
image = collection.mosaic()

tasklist = batch.image.toDriveByFeature(image, collection=fc, property='site', folder='Result_test_S5P', name='test', scale=305, dataType='float')

tasklist.start()`

And the Error:
`---------------------------------------------------------------------------
EEException                               Traceback (most recent call last)
<ipython-input-2-58d15af5f43d> in <module>
      6 
      7 feature = ee.Geometry.Polygon([[-20.3014885, -51.5035369], [-20.84233950, -51.6313196], [-20.6922002, -51.2336120], [-20.5804476, -52.1965132]]), {'site': 1}
----> 8 fc = ee.FeatureCollection(feature)
      9 collection = ee.ImageCollection("COPERNICUS/S5P/NRTI/L3_CLOUD").select('cloud_optical_depth').filterDate('2019-09-10', '2019-09-13').filterBounds(fc.geometry())
     10 image = collection.mosaic()

~\AppData\Local\Continuum\miniconda3\envs\S5P-37\lib\site-packages\ee\computedobject.py in __call__(cls, *args, **kwargs)
     30       return args[0]
     31     else:
---> 32       return type.__call__(cls, *args, **kwargs)
     33 
     34 

~\AppData\Local\Continuum\miniconda3\envs\S5P-37\lib\site-packages\ee\featurecollection.py in __init__(self, args, opt_column)
     62       super(FeatureCollection, self).__init__(
     63           apifunction.ApiFunction.lookup('Collection'), {
---> 64               'features': [feature.Feature(i) for i in args]
     65           })
     66     elif isinstance(args, ee_list.List):

~\AppData\Local\Continuum\miniconda3\envs\S5P-37\lib\site-packages\ee\featurecollection.py in <listcomp>(.0)
     62       super(FeatureCollection, self).__init__(
     63           apifunction.ApiFunction.lookup('Collection'), {
---> 64               'features': [feature.Feature(i) for i in args]
     65           })
     66     elif isinstance(args, ee_list.List):

~\AppData\Local\Continuum\miniconda3\envs\S5P-37\lib\site-packages\ee\computedobject.py in __call__(cls, *args, **kwargs)
     30       return args[0]
     31     else:
---> 32       return type.__call__(cls, *args, **kwargs)
     33 
     34 

~\AppData\Local\Continuum\miniconda3\envs\S5P-37\lib\site-packages\ee\feature.py in __init__(self, geom, opt_properties)
     75       # turning out to be GeoJSON.
     76       super(Feature, self).__init__(feature_constructor, {
---> 77           'geometry': geometry.Geometry(geom),
     78           'metadata': opt_properties or None
     79       })

~\AppData\Local\Continuum\miniconda3\envs\S5P-37\lib\site-packages\ee\computedobject.py in __call__(cls, *args, **kwargs)
     30       return args[0]
     31     else:
---> 32       return type.__call__(cls, *args, **kwargs)
     33 
     34 

~\AppData\Local\Continuum\miniconda3\envs\S5P-37\lib\site-packages\ee\geometry.py in __init__(self, geo_json, opt_proj, opt_geodesic, opt_evenOdd)
     81 
     82     if not Geometry._isValidGeometry(geo_json):
---> 83       raise ee_exception.EEException('Invalid GeoJSON geometry.')
     84 
     85     super(Geometry, self).__init__(None, None)

EEException: Invalid GeoJSON geometry.`

I also tried importing the geometry as shapefile and as a geojson through geopandas, still got the same error. Not sure if this is a gee-tools error or an ee error. Can you help me?

I am new to python so hopefully it's just me doing something wrong...
Thanks in advance.

**Comment by fitoprincipe** [comment]
Hi @Henrique165 

I closed the issue with the commit. The function has changed a bit, to match the new way I am implementing batch processes. In the `name` parameter you have to use a pattern, in your case should be:

``` python
tasklist = batch.image.toDriveByFeature(image, collection=fc, folder='Result_test_S5P', name='test {site}', scale=305, dataType='float')
```
Every `Feature` in your collection should have a property called `site` holding the site name.

**Comment by Henrique165** [comment]
Thank you!

**Comment by fitoprincipe** [comment]
I still have to push to pypi so you can update via pip

**Comment by fitoprincipe** [comment]
Done
