### ISSUE TITLE
Export to Drive

### ISSUE THREAD

**Issue by mm46655** [gee-community/gee_tools#41]
Hello,

I've tried exporting a couple of different ways but seem to have no luck. I tried using the _exportByFeat.ipynb_ as a guide and followed the script as is but I get the same result.  The correct folder is created in my drive but there is nothing inside. Am I doing anything wrong?

**Comment by fitoprincipe** [comment]
Hi @mm46655 , I suppose you have solved it since you closed it. You can follow your tasks using the `TaskManager` in [ipygee](https://github.com/fitoprincipe/ipygee). Cheers =)

**Comment by mm46655** [comment]
Hi Rodrigo! Yes your code worked correctly it just took longer than I expected. I am still having some trouble with my own image exportation though. I was just trying to export an image from the your other script _GEE Best Available Pixel_. I am having trouble viewing the image either in true color format or single band. Would it be possible to email you directly or show you my py script?

**Comment by fitoprincipe** [comment]
Hi @mm46655 , yes, I am quite busy lately, but I'll see what I can do. My email is fitoprincipe82 at gmail. =)
