### ISSUE TITLE
bugs: Map = Map()

### ISSUE THREAD

**Issue by ZoeM2016** [gee-community/gee_tools#42]
Hi Rodrigo,
When i try your code on google colab,an error occured. 
IndexError                                Traceback (most recent call last)
<ipython-input-26-77f14f4097a3> in <module>()
      3 i = ee.Image('COPERNICUS/S2/20181122T142749_20181122T143353_T18GYT').clip(aoi)
      4 grid = tools.image.toGrid(i, 3, geometry=aoi)
----> 5 Map = Map()
      6 
      7 Map.show()

1 frames
/usr/local/lib/python3.6/dist-packages/ipygee/assets.py in __init__(self, map, **kwargs)
     20         # Thumb height
     21         self.thumb_height = kwargs.get('thumb_height', 300)
---> 22         self.root_path = ee.data.getAssetRoots()[0]['id']
     23 
     24         # Map

IndexError: list index out of range

Could you please help me about it?

**Comment by fitoprincipe** [comment]
Hi @ZoeM2016 , I don't think `Map` will work in google Colab, I don't think so. `AssetManager` and `TaskManager` may work. Have you tried `Map` in a Jupyter notebook?

**Comment by berlin-young** [comment]
Hi Rodrigo,
when I use your code in anaconda ,a same errror occured
input: 
mayMap=Map()
Map.show()
self.root_path = ee.data.getAssetRoots()[0]['id']
IndexError: list index out of range
(I run in my local python environment, and the required environment is set)
could you help me adress it?

**Comment by fitoprincipe** [comment]
Hi @berlin-young,
as I said in the last comment, all jupyter related code has been moved to another package: [ipygee](https://github.com/fitoprincipe/ipygee). You can post an issue there. Thank you =)

**Comment by 12rambau** [comment]
Dear both, the Map method is now living in geemap and ipygee packages. please have a look at them.
