### ISSUE TITLE
bug: Missing return in batch.Export.imagecollection.toDrive

### ISSUE THREAD

**Issue by fpaludi** [gee-community/gee_tools#43]
Documentation saids that the function will return a list of tasks
```
:return: list of tasks
:rtype: list
```
but there is not return at the end of the function.

As the list of tasks is already created, it is just necessary to add :

`
return tasklist
`

at the end of the function

**Comment by fitoprincipe** [comment]
Hello @fpaludi ,
you are right =) I have just fixed it.
