### ISSUE TITLE
batch = require('users/fitoprincipe/geetools:batch')

### ISSUE THREAD

**Issue by valb21** [gee-community/gee_tools#44]
Hi,

I'm contacting you because I have a problem with geetools. 
I'm working on jupyter with anaconda 3.

Here my code :

```
## Init ##
from IPython.display import Image
import ee
import folium
from geetools import batch
import datetime

ee.Initialize()

parcelle = ee.Geometry.Rectangle([[xxxxxxx,xxxxxx],[xxxxxxx,xxxxxxx]])

def addNDVI(image):
    ndvi=(image.expression('float(b("B4") - b("B3")) / (b("B4") + b("B3"))')
    .rename('NDVI'))
    return image.addBands(ndvi)

collection = (ee.ImageCollection('LANDSAT/LE07/C01/T1_SR')
              .filterDate(datetime.datetime(2000,1,1),
                         datetime.datetime(2020,3,3))
              .filterBounds(parcelle)
              .select(['B4', 'B3'])
              .map(addNDVI).select('NDVI'));

batch.ImageCollection.toDrive(collection, 'Landsat7',
                                      {scale: 30,
                                      region: parcelle.getInfo()["coordinates"],
                                      type: 'float'})

```

And I'm getting the following error: 

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-fde281556d5e> in <module>
----> 1 batch.ImageCollection.toDrive(collection, 'Landsat7',
      2                                       {scale: 30,
      3                                       region: parcelle.getInfo()["coordinates"],
      4                                       type: 'float'})

AttributeError: module 'geetools.batch' has no attribute 'ImageCollection'
```

Could you help me ?

**Comment by valb21** [comment]
I resolved the problem.

It works with

`batch.imagecollection.toDrive(collection, folder='Landsat7', region=parcelle.getInfo()["coordinates"], scale=30, verbose=True)`

Thanks for your work :).

**Comment by fitoprincipe** [comment]
Hi @valb21,

The issue was due to using the JS syntax of [`geetools`](https://github.com/fitoprincipe/geetools-code-editor/wiki/Batch#imagecollectiontodrivecollection-folder-options) and not the python syntax. You've solved it that way. Great

**Comment by fitoprincipe** [comment]
Thank you for reporting the issue  =). Best regards. Closing now

**Comment by gobinathp** [comment]
```
var batch = require('users/fitoprincipe/geetools:batch');

// whole study period------------------------------------------------------------------------------
var dataset = ee.ImageCollection('MODIS/006/MYD13Q1')
                  .filter(ee.Filter.date('2002-04-07', '2016-12-31'))
                  .filterBounds(study)
                  .map(function(image){return image.clip(study)}) ;
var ndvi = dataset.select('NDVI');
var ndviVis = {
  min: 0.0,
  max: 8000.0,
  palette: [
    'FFFFFF', 'CE7E45', 'DF923D', 'F1B555', 'FCD163', '99B718', '74A901',
    '66A000', '529400', '3E8601', '207401', '056201', '004C00', '023B01',
    '012E01', '011D01', '011301'
  ],
};
print(ndvi);


//adding layers
Map.addLayer(ndvi, ndviVis, 'NDVI');


// Export the image, specifying scale and region.
batch.Download.ImageCollection.toDrive(ndvi, 'Gobi_EE', 
                {
                  scale: 1000,
                  region: study
})

```

> Defined a simple boundaries in the name of study, want to batch export the MODIS dataset, dont know where I'm doing mistake can you please help on this

**Comment by fitoprincipe** [comment]
are you in the code editor (JavaScript) @gobinathp? what is the error?

**Comment by gobinathp** [comment]
> are you in the code editor (JavaScript) @gobinathp? what is the error ?

I found the error and cleared it sir. Thank you.

**Comment by ytarazona** [comment]
Hello @fitoprincipe , Would you be so kind as to help me?

I am interested in downloading Sentinel-1 images using this script:

import ee
ee.Authenticate()
ee.Initialize()

import geetools

# Region
region = ee.Geometry.Rectangle([-64.1569659949999931,-8.8276458170000005, 
                                -63.7711738149999974,-8.5146591039999997])

# Dates
start_date = ee.Date('2019-05-01')
finish_date = ee.Date('2019-05-7')
orbit = 'ASCENDING'

# Get the VV collection.
collectionS1 = ee.ImageCollection('COPERNICUS/S1_GRD')\
    .filter(ee.Filter.listContains('transmitterReceiverPolarisation', 'VV'))\
    .filter(ee.Filter.eq('instrumentMode', 'IW'))\
    .filterDate(start_date, finish_date)\
    .filterBounds(region)

# Get the VV collection.
collectionVV = collectionS1.select('VV')

#  Folder
folder = 'GEE'

#  Download Collections
geetools.batch.imagecollection.toDrive(collectionVV, folder=folder, scale=10, maxPixels=1e13,
                 region=region)


It works well, however two folders with the same name are downloaded, and the total of the downloaded images are in both folders. 

Why does this happen?

Thank you so much for your time

Best,
Yonatan

**Comment by ytarazona** [comment]
`r`
