### ISSUE TITLE
ImageCollection Export to Cloud Storage

### ISSUE THREAD

**Issue by joshdaniel** [gee-community/gee_tools#46]
The ImageCollection Export to Drive function seems useful. I think it would be useful to add similar methods for other export destinations. My particular use case requires ImageCollection Export to Cloud Storage, which doesn't seem to be implemented here or on base EE. There may be other export methods missing from EE that would be useful here as well.

(Also, thanks for the neat library!)

**Comment by agustiin** [comment]
> The ImageCollection Export to Drive function seems useful. I think it would be useful to add similar methods for other export destinations. My particular use case requires ImageCollection Export to Cloud Storage, which doesn't seem to be implemented here or on base EE. There may be other export methods missing from EE that would be useful here as well.
> 
> (Also, thanks for the neat library!)

It's already implemented in EE base and here in [geetools/batch/imagecollection.py](https://github.com/gee-community/gee_tools/blob/fb7168a369507e346b0b858f17263c5573b58c6f/geetools/batch/imagecollection.py) (toCloudStorage method)!

**Comment by fitoprincipe** [comment]
It was added in #38 . Thanks @agustiin =) Cheers
