### ISSUE TITLE
Using maxImgs parameter gives EEException

### ISSUE THREAD

**Issue by carderne** [gee-community/gee_tools#47]
If I include the `maxImgs` parameter in a call to `batch.Export.imagecollection.toDrive`, I get the following error: `EEException: Unknown configuration options: {'maxImgs': 20}.`.

**Comment by fitoprincipe** [comment]
Hi @carderne , thank you for pointing this out. Yes, I left the parameter in the docs, but it is not used anymore. You can limit the number of images using the method `limit` of the `ImageCollection` object. For more info: `help(ee.ImageCollection.limit)`. Cheers
