### ISSUE TITLE
B10 in sentinel is not available

### ISSUE THREAD

**Issue by jpardila** [gee-community/gee_tools#49]
I tried running hollsteinMask but it requires B10 in sentinel2. It seems this was removed from the GEE collection.

**Comment by fitoprincipe** [comment]
Hi @jpardila , you are right, B10 is not present in Sentinel 2 Level 2-A (SR), but it is still present in Level 1-C (TOA). In SR collection you have SCL classification band that holds information for clouds, shadows, cirrus, water and snow.
