### ISSUE TITLE
Cloud Mask

### ISSUE THREAD

**Issue by ricardobarroslourenco** [gee-community/gee_tools#5]
Hi Rodrigo!

It seems very interesting the library you've written. I'm looking for more information on how to use the cloud mask functionality. Could you give me an example?

**Comment by fitoprincipe** [comment]
Hi Ricardo,
Some examples are in the tests (geetools/test/...)

``` python
from geetools import cloud_mask

# one image
l8toa = ee.Image("LANDSAT/LC8_L1T_TOA_FMASK/LC82310902013344LGN00")
masked_l8toa = cloud_mask.fmask("fmask")(l8toa)

sentinel2 = ee.Image("COPERNICUS/S2/20160122T144426_20160127T174646_T18GYT")
masked_sentinel2 = cloud_mask.sentinel2(sentinel2)

# an imagecollection
l8toa_col = ee.ImageCollection("LANDSAT/LC8_L1T_TOA_FMASK")
masked_l8toa_col = l8toa_col.map(cloud_mask.fmask("fmask"))

sentinel2_col = ee.ImageCollection("COPERNICUS/S2")
masked_sentinel2_col = l8toa_col.map(cloud_mask.sentinel2)
```

**Comment by ricardobarroslourenco** [comment]
Thank you :) 

If I want to apply on MODIS (MOD09GA) is it compatible? Or I need to use regular bitwise masking?

**Comment by aldosales** [comment]
Hi guys, 

I don´t know if you could see, but the "fmask" got out from the GEE.  Which alternatives are you using to get out the cloud from the images?

**Comment by fitoprincipe** [comment]
Hi @aldosales, yes, fmask is retired :smile: But I updated the package for the new SR and TOA collections (`LANDSAT/LC08/C01/T1_SR` for example). See https://github.com/gee-community/gee_tools/blob/cd4dc2221db527c908637d36bffcc4bc9a02adb0/geetools/cloud_mask.py#L155 and https://github.com/gee-community/gee_tools/blob/cd4dc2221db527c908637d36bffcc4bc9a02adb0/geetools/cloud_mask.py#L183

**Comment by fitoprincipe** [comment]
Hi @ricardobarroslourenco, there is a function for MODIS too: https://github.com/gee-community/gee_tools/blob/cd4dc2221db527c908637d36bffcc4bc9a02adb0/geetools/cloud_mask.py#L33

**Comment by aldosales** [comment]
Thanks man! Are they working for L5 and L7 too?

**Comment by fitoprincipe** [comment]
Yes @aldosales, it can work with L 4 5 7 and 8, SR or TOA. I also recommend you https://github.com/fitoprincipe/geetools-code-editor, it is not complete yet, but will be as soon as I can update it.

**Comment by ricardobarroslourenco** [comment]
I think that this is already solved.
