### ISSUE TITLE
Duplicated folder when downloading an ImageCollection to Google Drive

### ISSUE THREAD

**Issue by fitoprincipe** [gee-community/gee_tools#58]
Hello @fitoprincipe , Would you be so kind as to help me?

I am interested in downloading Sentinel-1 images using this script:

```
import ee
ee.Authenticate()
ee.Initialize()

import geetools

region = ee.Geometry.Rectangle([-64.1569659949999931,-8.8276458170000005, 
                                -63.7711738149999974,-8.5146591039999997])

start_date = ee.Date('2019-05-01')
finish_date = ee.Date('2019-05-7')
orbit = 'ASCENDING'

collectionS1 = ee.ImageCollection('COPERNICUS/S1_GRD')\
    .filter(ee.Filter.listContains('transmitterReceiverPolarisation', 'VV'))\
    .filter(ee.Filter.eq('instrumentMode', 'IW'))\
    .filterDate(start_date, finish_date)\
    .filterBounds(region)

collectionVV = collectionS1.select('VV')

folder = 'GEE'

geetools.batch.imagecollection.toDrive(collectionVV, folder=folder, scale=10, maxPixels=1e13,
                 region=region)
```

It works well, however two folders with the same name are downloaded, and the total of the downloaded images are in both folders. 

Why does this happen?

Thank you so much for your time

Best,
Yonatan

_Originally posted by @ytarazona in https://github.com/gee-community/gee_tools/issues/44#issuecomment-752683333_

**Comment by fitoprincipe** [comment]
Hola @ytarazona, what version of `geetools` are you using. I have checked the code of the latest version (0.6.7) and everything looks fine. I'll try to replicate the error

**Comment by ytarazona** [comment]
Hola @fitoprincipe, thanks for your response. I installed the last [version](https://github.com/gee-community/gee_tools) two hours ago. 
When I try to download five o four images two folders apper on my drive, but when I download several images (more than 10, 20, 30) I don not that problem.  I guess it's because of the speed of my connection. 

An excellent and very useful package!

**Comment by fitoprincipe** [comment]
Thank you @ytarazona ! =) I have tested the code, and you are right. But the created folders have the same name, and the process that function does is not big deal.. so my first guess is that it is an issue in GEE side, and not `geetools`.
Basically I call  `ee.batch.Export.image.toDrive` as many times as images in the collection, but I set the `folder` parameter with only one name every time. So, I really don't know what is happening 🤔

**Comment by ytarazona** [comment]
Thank you @fitoprincipe for your explanation. Everything is working well now. I guess that issue was on the GEE side 👍 .
Thank you again for this tools, it is very useful!. Please check out your linkedin because i would like to collaborate on a python package.

Best,
Yonatan
