### ISSUE TITLE
An issue with hollstein_S2

### ISSUE THREAD

**Issue by thanhgis** [gee-community/gee_tools#6]
Dear Rodrigo,

Thank you very much for your gee_tools library for python. I am trying to utilize it into my study.

It is okay to map with s2ESA (cloud_mask.sentinel2) without error, however when I map with s2holl (cloud_mask.hollstein_S2), my app produce this error: **Invalid argument specified for ee.List(): hollstein**

Could you please guide me how to fix? Or did I do something wrong?

Thank you!

**Comment by fitoprincipe** [comment]
Hello @thanhgis,

What version of gee_tools are you using?

```
import geetools
print(geetools.__version__)
```
If the version you are using has Hollstein, `ee_collection.map(cloud_mask.sentinel2)` shouldn't work, should give you the same error as Hollstein function. This is because in the later version I made all functions return a function. So:

```
from geetools import cloud_mask

S2_function = cloud_mask.sentinel2()
Hollstein_function = cloud_mask.hollstein_S2()

# Now you can map those functions
col = ee.ImageCollection('COPERNICUS/S2')

# Filter collection here

# Apply cloud mask from the BQA band
masked_col = col.map(S2_function)

# Apply Hollstein's cloud masking
masked_holl = col.map(Hollstein_function)

# Mix both
masked_both = masked_col.map(Hollstein_function)
```

**Comment by thanhgis** [comment]
Thank you for your quick response. 

I've just installed your geetools yesterday, and its version is 0.0.9. Is it latest one?

I tried: 
from geetools import cloud_mask

s2holl = cloud_mask.hollstein_S2()
s2ESA = cloud_mask.sentinel2()
collection = ee.ImageCollection('COPERNICUS/S2')
# My filter with dates and bounds here
mask_coll_esa = collection.map(s2ESA) # <----- This works
mask_coll_holl = collection.map(s2holl) # <----- This produces error: "Invalid argument......."

Should I mix both funtions?

**Comment by fitoprincipe** [comment]
It's a bug. I am working on it. I let you know when it's finished. Thanks

**Comment by fitoprincipe** [comment]
I found the issue. It wasn't geetools, you have to upgrade earthengine-api in order to make hollstein work. I found the 'bug' and could try to fix it, but I think is better to go ahead and upgrade packages.

**Comment by thanhgis** [comment]
Thanh you Rodrigo, 

I upgraded my earthengine-api and geetools is working now.

**Comment by fitoprincipe** [comment]
Great!
