### ISSUE TITLE
name pattern issue

### ISSUE THREAD

**Issue by WHBSpeiser** [gee-community/gee_tools#60]
Hi! Used to work in the past, but when I batch export sentinel imagery with only '{:system_date:}' as the name pattern the imagery all exports as ":system_date:" rather than its respective name e.g. "2017-01-12"

**Comment by WHBSpeiser** [comment]
Seems to be an issue with sentinel as landsat works just fine...

**Comment by fitoprincipe** [comment]
Hi @WHBSpeiser , did you solve the issue?? May be a bit late, but the pattern should be: `{system_date}` without the `:`. Let me know =)

**Comment by WHBSpeiser** [comment]
Hey! So after some time away from the code, I just retried it and tinkered with it and my issue appears to be that I was running a mathematical operation to the collection in GEE which must have altered the system_date metadata. My fault :)! Thanks for this tool kit, it has been invaluable!
