### ISSUE TITLE
AttributeError: type object 'Export' has no attribute 'ImageCollection'

### ISSUE THREAD

**Issue by rdriveras** [gee-community/gee_tools#66]
Hi! You are saving my life with these tools. Thank you in advance! 
Sorry to ask but, I keep getting this error at the moment of exporting 10 images to my Drive. My code looks like this:

```ruby
from geetools import batch
import ee
ee.Initialize()
zona_aire = ee.FeatureCollection("users/romeldrivera/zona_aire")
start = ee.Date.fromYMD(2018,1,1)
days = ee.List.sequence(0,9)
def one(d):
    return start.advance(d,'day')
startDates = days.map(one)
def three(img):
    return img.clip(zona_aire)
def two(m):
    start = ee.Date(m)
    end = ee.Date(m).advance(1,'day')
    date_range = ee.DateRange(start,end)
    MODISday = ee.ImageCollection('MODIS/006/MCD19A2_GRANULES').select('Optical_Depth_047').filterDate(date_range).map(three)
    return(MODISday.median())
daymap = two
list_of_images = startDates.map(daymap)
mt = ee.ImageCollection(list_of_images)
tasks = batch.Export.ImageCollection.toDrive(mt, 'AOD2018', scale=30, region=zona_aire.getInfo()["coordinates"])
```
I run that code and get 

_tasks = batch.Export.ImageCollection.toDrive(mt, 'AOD2018', scale=30, region=zona_aire.getInfo()["coordinates"])
AttributeError: type object 'Export' has no attribute 'ImageCollection'_

I appreciate your time and attention!

**Comment by fitoprincipe** [comment]
Hi @rdriveras, you are welcome =)
I guess the only issue is the uppercase C, should be: `batch.Export.imagecollection.toDrive`
Let me know

**Comment by rdriveras** [comment]
Yeah! That was the issue, sorry for that. Thank you very much again!
