### ISSUE TITLE
addlayer for feature won't work using ipymap?

### ISSUE THREAD

**Issue by MatthieuStigler** [gee-community/gee_tools#7]
Hi

great tools , thanks a lot! Is it possible that `addLayer` cannot show `Features` on map, only geometries? I got warning message *TypeError: addGeoJson() takes exactly 2 arguments (1 given)* on a Feature. When using on FeatureCollection, I get: *addLayer doesn't support adding the specified object to the map*.

See:

```python
import ee
ee.Initialize()
rectangle = ee.Geometry.Rectangle([-40, -20, 40, 20]);
rectangle_f = ee.Feature(rectangle)
rectangle_fc = ee.FeatureCollection(rectangle_f)

from geetools import ipymap
Map2 = ipymap.Map()

Map2.show()
Map2.addLayer(rectangle, {}, 'rectangle')
Map2.centerObject(rectangle)
```

All works fine. But now these two will throw an error?

```python
Map2.addLayer(rectangle_f, {}, 'rectangle feature')
Map2.addLayer(rectangle_fc, {}, 'rectangle feature')
```

**Comment by fitoprincipe** [comment]
Hi @MatthieuStigler ,
Than you for using the tool, it's great to know somebody is using the ipymap tool and giving some feedback!

About the FeatureCollection yes, I have not implemented yet adding FC to the Map, but Features should work. How did you install geetools? via pip?

**Comment by MatthieuStigler** [comment]
Hi

Yes, installed via pip (within a conda environment). Does it mean I am not using the most recent (dev?) version? 
Are you not getting the error message *TypeError: addGeoJson() takes exactly 2 arguments (1 given)*? 

Thanks

**Comment by fitoprincipe** [comment]
Hi @MatthieuStigler, yes, it is solved in the develop branch, but I couldn't merge branches yet. In case you don't know how to use the dev branch:

## Installing the package

- clone the repo
  - `git clone https://github.com/gee-community/gee_tools`
- checkout dev branch
  - `cd gee_tools`
  - `git checkout develop`
- being on the repo folder in the terminal
  - `sudo pip install .`

## Not installing the package

- Set the cloned repo into the PYTHONPATH environment variable (be careful with this)
  - https://stackoverflow.com/questions/3701646/how-to-add-to-the-pythonpath-in-windows
  - https://scipher.wordpress.com/2010/05/10/setting-your-pythonpath-environment-variable-linuxunixosx/
- checkout dev branch
  - `git checkout develop`

**Comment by MatthieuStigler** [comment]
Hi!

Thanks for the detailed instructions, and for solving the issue!

I installed the dev version, and indeed it does now work on features, nice!
 
Thanks a lot for the valuable work
