### ISSUE TITLE
Batch download stopped working

### ISSUE THREAD

**Issue by oleksandrkarasov** [gee-community/gee_tools#72]
Hi,
I've been using this code for a long time, and today it stopped working https://code.earthengine.google.com/2e38ff1b7dc0d006715a085cb469ec90 . If shortly: 
1) I upload the Sentinel-2 dataset, 
2) do cloud masking and calculate vegetation indices, 
3) calculate the number of valid pixels within the region and filter out images with less than 100 valid pixels.
4) batch download of the resulted vegetation indices.

Today, batch download stopped working with step 3: I get notification "An internal error has occurred (request: 44215952-a82b-4627-9be7-844555231e66)"; at the same time, the batch download runs only for 2-5 files (out of 12).
If I skip step 3, the code runs properly and the batch download works fine. I have reported this problem in the GEE feedback field, but I don't know how long it will take. Maybe you could help me understand the reason for the problem and provide some solution?
I really appreciate any help you can provide.

**Comment by fitoprincipe** [comment]
Hello @oleksandrkarasov , I haven't change anything in the code.. I has to be something related to GEE itself 🤔

**Comment by fitoprincipe** [comment]
Anyways, this repository is for the Python API, the one for the JS API is: https://github.com/fitoprincipe/geetools-code-editor/issues

**Comment by 12rambau** [comment]
I'll close this one as it's unrelated to the Python implementation
