### ISSUE TITLE
BadZipFile error when downloading sentinel2 using geemap

### ISSUE THREAD

**Issue by vanthinh1711** [gee-community/gee_tools#75]
I am downloading sentinel2 images to my local computer using geemap tool. The program runs smoothly for some days. But then, sometimes, I have the error "BadZipFile: File is not a zip file".  Please suggest a solution. Thank you
![badzipfile_error](https://user-images.githubusercontent.com/63662330/197093876-5137a3de-b224-45b0-9110-33c80da76919.png)

**Comment by 12rambau** [comment]
Our package is never called in your traceback I suggest (if the error still persists) that you turn to the geemap repository.
