### ISSUE TITLE
refactoring proposal

### ISSUE THREAD

**Issue by 12rambau** [gee-community/gee_tools#79]
I'm starting to use the geetools lib. the content is super useful but if you were not there the moment you started the lib, it's rapidely becomijng complicated to catch up with all the available tools and how they should be used. 

I would be happy to participate in a refactoring effort but first I wanted to know if you would find the following pattern useful: 

Let's say I want to create a `FeatureCollection` from a shapefile, I would need to use the following 
```python 
import geetools

fc = geetools.batch.featurecollection.fromShapefile("toto.shp")
```

Which is kinda breaking the GEE pattern. What if instead we could do: 
```python 
import geetools as gee 

fc = geetools.FeatureCollection.fromShapeFile("toto.shp")
```

By doing so the lib would keep up with recent development of the GEE API by being an extension lib more than an independent package and keep the pattern used by google team with classes of class. 

what do you think ?

**Comment by fitoprincipe** [comment]
I think it's a good idea @12rambau :)

**Comment by 12rambau** [comment]
I will move all my developments to the 1.x branch so that when we are satisfied with the result we can release it. 
As it will be a sementic change, people will have easy ways to mitigate the changes
