### ISSUE TITLE
add a new maintainer to the repository 

### ISSUE THREAD

**Issue by 12rambau** [gee-community/gee_tools#80]
Hi @giswqs, 

I’m @12rambau. We came across each other in open-source repository like ipyleaflet and locatileserver.
I would like to go and refactor geetools to modernize its structure and the way methods are called within the API (#79).

To avoid pinging people all the time and set up hooks to global services (namely codecov and RDT) I would need to have access to the repository as a maintainer. Would you mind adding me in the organization and provide me some rights on the repo ? @fitoprincipe already agreed but he lost his admin rights  when he transferred the repository to the organization.

We can also discuss this matter via mail if you want pierrick.rambaud49@gmail.com

Side note: In the sphinx-contrib organization we use a special repository for admin question (https://github.com/sphinx-contrib/github-administration) maybe you could create one for gee-community ?

**Comment by fitoprincipe** [comment]
thank you @giswqs and @12rambau :)
